ModuleInfo "Name: muttley.INIFileHandler"
ModuleInfo "Version: 1.0.5"
ModuleInfo "License: GNU Lesser General Public License"
ModuleInfo "Author: Paul Maskelyne (Muttley)"
ModuleInfo "Copyright: (C) 2007 Paul Maskelyne"
ModuleInfo "E-Mail: muttley@muttleyville.org"
ModuleInfo "Website: http://www.muttleyville.org"
ModuleInfo "History: 1.0.5"
ModuleInfo "History: Missing sections and parameters are now created correcty when trying to set them and CreateMissingEntries() is set to True"
ModuleInfo "History: 1.0.4"
ModuleInfo "History: Added support for string based Booleans as BlitzMax doesn't have a proper bool datatype"
ModuleInfo "History: 1.0.3 (Release)"
ModuleInfo "History: Missing parameters that are requested can now be automatically added to ini file by using CreateMissingEntries()"
ModuleInfo "History: 1.0.2"
ModuleInfo "History: Get* methods can now take default values which are returned if the requested parameter doesn't exist"
ModuleInfo "History: 1.0.1"
ModuleInfo "History: No longer writing Global and Section comments to INI file when comment is blank"
ModuleInfo "History: 1.0.0 (Release)"
ModuleInfo "History: Initial Release"
import brl.blitz
import brl.filesystem
import brl.system
import brl.linkedlist
import brl.standardio
import brl.retro
TINISection^brl.blitz.Object{
.Name$&
.comment$&
.Lparameters:brl.linkedlist.TList&
-New%()="_muttley_inifilehandler_TINISection_New"
-Delete%()="_muttley_inifilehandler_TINISection_Delete"
-AddParameter%(_name$)="_muttley_inifilehandler_TINISection_AddParameter"
-DeleteParameter%(_name$)="_muttley_inifilehandler_TINISection_DeleteParameter"
-GetComment$()="_muttley_inifilehandler_TINISection_GetComment"
-GetName$()="_muttley_inifilehandler_TINISection_GetName"
-GetParameterComment$(_name$)="_muttley_inifilehandler_TINISection_GetParameterComment"
-GetParameters$&[]()="_muttley_inifilehandler_TINISection_GetParameters"
-GetStringValue$(_name$)="_muttley_inifilehandler_TINISection_GetStringValue"
-GetStringValues$&[](_name$)="_muttley_inifilehandler_TINISection_GetStringValues"
-ParameterExists%(_parameter_name$)="_muttley_inifilehandler_TINISection_ParameterExists"
-Save%(out:brl.stream.TStream)="_muttley_inifilehandler_TINISection_Save"
-SetComment%(_comment$)="_muttley_inifilehandler_TINISection_SetComment"
-SetName%(_name$)="_muttley_inifilehandler_TINISection_SetName"
-SetParameterComment%(_name$,_comment$)="_muttley_inifilehandler_TINISection_SetParameterComment"
-SetStringValue%(_name$,_value$)="_muttley_inifilehandler_TINISection_SetStringValue"
-SetStringValues%(_name$,_values$&[])="_muttley_inifilehandler_TINISection_SetStringValues"
-SortParameters%()="_muttley_inifilehandler_TINISection_SortParameters"
}="muttley_inifilehandler_TINISection"
TINIParameter^brl.blitz.Object{
.Name$&
.Lvalues:brl.linkedlist.TList&
.comment$&
-New%()="_muttley_inifilehandler_TINIParameter_New"
-Delete%()="_muttley_inifilehandler_TINIParameter_Delete"
+CheckValue$(_value$)="_muttley_inifilehandler_TINIParameter_CheckValue"
+Create:TINIParameter(_name$)="_muttley_inifilehandler_TINIParameter_Create"
-GetComment$()="_muttley_inifilehandler_TINIParameter_GetComment"
-GetName$()="_muttley_inifilehandler_TINIParameter_GetName"
-GetStringValue$()="_muttley_inifilehandler_TINIParameter_GetStringValue"
-GetStringValues$&[]()="_muttley_inifilehandler_TINIParameter_GetStringValues"
-Save%(out:brl.stream.TStream)="_muttley_inifilehandler_TINIParameter_Save"
-SetComment%(_comment$)="_muttley_inifilehandler_TINIParameter_SetComment"
-SetName%(_name$)="_muttley_inifilehandler_TINIParameter_SetName"
-SetStringValue%(_value$)="_muttley_inifilehandler_TINIParameter_SetStringValue"
-SetStringValues%(_values$&[])="_muttley_inifilehandler_TINIParameter_SetStringValues"
}="muttley_inifilehandler_TINIParameter"
TINIValue^brl.blitz.Object{
.value$&
-New%()="_muttley_inifilehandler_TINIValue_New"
-Delete%()="_muttley_inifilehandler_TINIValue_Delete"
-GetStringValue$()="_muttley_inifilehandler_TINIValue_GetStringValue"
-SetStringValue%(_value$)="_muttley_inifilehandler_TINIValue_SetStringValue"
}="muttley_inifilehandler_TINIValue"
TINIFile^brl.blitz.Object{
.Filename$&
.comment$&
.Lsections:brl.linkedlist.TList&
.createWhenMissing%&
-New%()="_muttley_inifilehandler_TINIFile_New"
-Delete%()="_muttley_inifilehandler_TINIFile_Delete"
+Create:TINIFile(_filename$=$"config.ini")="_muttley_inifilehandler_TINIFile_Create"
-AddParameter%(_section_name$,_parameter$)="_muttley_inifilehandler_TINIFile_AddParameter"
-AddSection%(_name$,_comment$=$"")="_muttley_inifilehandler_TINIFile_AddSection"
-CreateMissingEntries%(bool%=1)="_muttley_inifilehandler_TINIFile_CreateMissingEntries"
-DeleteParameter%(_section_name$,_parameter$)="_muttley_inifilehandler_TINIFile_DeleteParameter"
-DeleteSection%(_name$)="_muttley_inifilehandler_TINIFile_DeleteSection"
-GetBoolValue%(_section_name$,_parameter_name$,defaultValue$=$"")="_muttley_inifilehandler_TINIFile_GetBoolValue"
-GetBoolValues%&[](_section_name$,_parameter_name$,defaultValues$&[]="bbEmptyArray")="_muttley_inifilehandler_TINIFile_GetBoolValues"
-GetByteValue@(_section_name$,_parameter_name$,defaultValue@=0)="_muttley_inifilehandler_TINIFile_GetByteValue"
-GetByteValues@&[](_section_name$,_parameter_name$,defaultValues@&[]="bbEmptyArray")="_muttley_inifilehandler_TINIFile_GetByteValues"
-GetComment$()="_muttley_inifilehandler_TINIFile_GetComment"
-GetDoubleValue!(_section_name$,_parameter_name$,defaultValue!=0!)="_muttley_inifilehandler_TINIFile_GetDoubleValue"
-GetDoubleValues!&[](_section_name$,_parameter_name$,defaultValues!&[]="bbEmptyArray")="_muttley_inifilehandler_TINIFile_GetDoubleValues"
-GetFilename$()="_muttley_inifilehandler_TINIFile_GetFilename"
-GetFloatValue#(_section_name$,_parameter_name$,defaultValue#=0#)="_muttley_inifilehandler_TINIFile_GetFloatValue"
-GetFloatValues#&[](_section_name$,_parameter_name$,defaultValues#&[]="bbEmptyArray")="_muttley_inifilehandler_TINIFile_GetFloatValues"
-GetIntValue%(_section_name$,_parameter_name$,defaultValue%=0)="_muttley_inifilehandler_TINIFile_GetIntValue"
-GetIntValues%&[](_section_name$,_parameter_name$,defaultValues%&[]="bbEmptyArray")="_muttley_inifilehandler_TINIFile_GetIntValues"
-GetLongValue%%(_section_name$,_parameter_name$,defaultValue%%=0:Long)="_muttley_inifilehandler_TINIFile_GetLongValue"
-GetLongValues%%&[](_section_name$,_parameter_name$,defaultValues%%&[]="bbEmptyArray")="_muttley_inifilehandler_TINIFile_GetLongValues"
-GetParameterComment$(_section_name$,_parameter$)="_muttley_inifilehandler_TINIFile_GetParameterComment"
-GetParameters$&[](_name$)="_muttley_inifilehandler_TINIFile_GetParameters"
-GetSectionComment$(_section_name$)="_muttley_inifilehandler_TINIFile_GetSectionComment"
-GetSections$&[]()="_muttley_inifilehandler_TINIFile_GetSections"
-GetShortValue@@(_section_name$,_parameter_name$,defaultValue@@=0)="_muttley_inifilehandler_TINIFile_GetShortValue"
-GetShortValues@@&[](_section_name$,_parameter_name$,defaultValues@@&[]="bbEmptyArray")="_muttley_inifilehandler_TINIFile_GetShortValues"
-GetStringValue$(_section_name$,_parameter_name$,defaultValue$=$"")="_muttley_inifilehandler_TINIFile_GetStringValue"
-GetStringValues$&[](_section_name$,_parameter_name$,defaultValues$&[]="bbEmptyArray")="_muttley_inifilehandler_TINIFile_GetStringValues"
-Load%()="_muttley_inifilehandler_TINIFile_Load"
-ParameterExists%(_section_name$,_parameter_name$)="_muttley_inifilehandler_TINIFile_ParameterExists"
-Save%(sortBeforeSave%=1)="_muttley_inifilehandler_TINIFile_Save"
-SectionExists%(_name$)="_muttley_inifilehandler_TINIFile_SectionExists"
-SetBoolValue%(_section_name$,_parameter$,_value$)="_muttley_inifilehandler_TINIFile_SetBoolValue"
-SetBoolValues%(_section_name$,_parameter$,_values$&[])="_muttley_inifilehandler_TINIFile_SetBoolValues"
-SetByteValue%(_section_name$,_parameter$,_value@)="_muttley_inifilehandler_TINIFile_SetByteValue"
-SetByteValues%(_section_name$,_parameter$,_values@&[])="_muttley_inifilehandler_TINIFile_SetByteValues"
-SetComment%(_comment$)="_muttley_inifilehandler_TINIFile_SetComment"
-SetDoubleValue%(_section_name$,_parameter$,_value!)="_muttley_inifilehandler_TINIFile_SetDoubleValue"
-SetDoubleValues%(_section_name$,_parameter$,_values!&[])="_muttley_inifilehandler_TINIFile_SetDoubleValues"
-SetFilename%(_filename$)="_muttley_inifilehandler_TINIFile_SetFilename"
-SetFloatValue%(_section_name$,_parameter$,_value#)="_muttley_inifilehandler_TINIFile_SetFloatValue"
-SetFloatValues%(_section_name$,_parameter$,_values#&[])="_muttley_inifilehandler_TINIFile_SetFloatValues"
-SetIntValue%(_section_name$,_parameter$,_value%)="_muttley_inifilehandler_TINIFile_SetIntValue"
-SetIntValues%(_section_name$,_parameter$,_values%&[])="_muttley_inifilehandler_TINIFile_SetIntValues"
-SetLongValue%(_section_name$,_parameter$,_value%%)="_muttley_inifilehandler_TINIFile_SetLongValue"
-SetLongValues%(_section_name$,_parameter$,_values%%&[])="_muttley_inifilehandler_TINIFile_SetLongValues"
-SetParameterComment%(_section_name$,_parameter$,_value$)="_muttley_inifilehandler_TINIFile_SetParameterComment"
-SetSectionComment%(_section_name$,_section_comment$)="_muttley_inifilehandler_TINIFile_SetSectionComment"
-SetShortValue%(_section_name$,_parameter$,_value@@)="_muttley_inifilehandler_TINIFile_SetShortValue"
-SetShortValues%(_section_name$,_parameter$,_values@@&[])="_muttley_inifilehandler_TINIFile_SetShortValues"
-SetStringValue%(_section_name$,_parameter$,_value$)="_muttley_inifilehandler_TINIFile_SetStringValue"
-SetStringValues%(_section_name$,_parameter$,_values$&[])="_muttley_inifilehandler_TINIFile_SetStringValues"
-Sort%()="_muttley_inifilehandler_TINIFile_Sort"
-SortParameters%(_section_name$)="_muttley_inifilehandler_TINIFile_SortParameters"
-SortSections%()="_muttley_inifilehandler_TINIFile_SortSections"
}="muttley_inifilehandler_TINIFile"
